xxhash64(CONCAT_WS('|',
    CAST(id AS STRING),
    COALESCE(display_name, ''),
    COALESCE(description, ''),
    COALESCE(funder_award_id, ''),
    COALESCE(CAST(amount AS STRING), ''),
    COALESCE(currency, ''),
    COALESCE(TO_JSON(funder), '{}'),
    COALESCE(funding_type, ''),
    COALESCE(funder_scheme, ''),
    COALESCE(provenance, ''),
    COALESCE(CAST(start_date AS STRING), ''),
    COALESCE(CAST(end_date AS STRING), ''),
    COALESCE(CAST(start_year AS STRING), ''),
    COALESCE(CAST(end_year AS STRING), ''),
    COALESCE(TO_JSON(lead_investigator), '{}'),
    COALESCE(TO_JSON(co_lead_investigator), '{}'),
    COALESCE(TO_JSON(investigators), '[]'),
    COALESCE(landing_page_url, ''),
    COALESCE(doi, ''),
    COALESCE(works_api_url, ''),
    COALESCE(TO_JSON(funded_outputs), '[]'),
    COALESCE(CAST(funded_outputs_count AS STRING), '0'),
    COALESCE(TO_JSON(primary_topic), '{}'),
    COALESCE(TO_JSON(topics), '[]'),
    COALESCE(TO_JSON(institution_awarded), '[]'),
    COALESCE(TO_JSON(institution_awarded_full), '[]'),
    COALESCE(TO_JSON(primary_topic_full), '{}'),
    COALESCE(TO_JSON(topics_full), '[]')
  ))
