-- GENERATED by scripts/gen_award_norm_key.py — DO NOT EDIT BY HAND.
-- Per-funder award-id translation key (oxjob #690), layered on the 2026-07-31
-- award-id-audit generic key. Family policy (merge onto newest year,
-- @kyle 2026-08-03) lives in the NOTEBOOKS (CreateAwards/WorkAwards) — this
-- file only defines keys, weakness, and verdicts.

-- Weakness predicate (review F1/F8): TRUE when a deposited string's NORMALIZED
-- form is a bare number at a dense-numeric-registry funder — such evidence is
-- never sufficient for an automatic merge. Single source of truth: WEAK_BARE.
CREATE OR REPLACE FUNCTION openalex.awards.award_id_is_weak(funder_id BIGINT, award_id STRING)
RETURNS BOOLEAN
RETURN
WITH _t AS (SELECT regexp_replace(regexp_replace(regexp_replace(UPPER(TRIM(award_id)), '[\\u2010-\\u2015\\u2212\\uFE58\\uFE63\\uFF0D]', '-'), '[\\u00A0\\u1680\\u2000-\\u200B\\u202F\\u205F\\u3000]', ' '), '  +', ' ') AS _n)
SELECT COALESCE((funder_id = 4320334506 AND _n rlike '^[0-9]{4,6}$') OR (funder_id = 4320311904 AND _n rlike '^[0-9]{5,6}$') OR (funder_id = 4320320924 AND _n rlike '^[0-9]{4,6}$') OR (funder_id = 4320320300 AND _n rlike '^[0-9]{6}$') OR (funder_id = 4320306076 AND _n rlike '^[0-9]{7}$') OR (funder_id = 4320334593 AND _n rlike '^[0-9]{4,6}$'), FALSE) FROM _t;

CREATE OR REPLACE FUNCTION openalex.awards.award_norm_key(funder_id BIGINT, award_id STRING, side STRING)
RETURNS STRING
RETURN
WITH _t AS (SELECT regexp_replace(regexp_replace(regexp_replace(UPPER(TRIM(award_id)), '[\\u2010-\\u2015\\u2212\\uFE58\\uFE63\\uFF0D]', '-'), '[\\u00A0\\u1680\\u2000-\\u200B\\u202F\\u205F\\u3000]', ' '), '  +', ' ') AS _n)
SELECT COALESCE(
  CASE WHEN side = 'registry' THEN
    CASE
      WHEN funder_id = 4320321001 THEN (NULLIF(regexp_extract(_n, '^(\\d{8})$', 1), ''))
      WHEN funder_id = 4320332161 THEN (NULLIF(regexp_extract(_n, '([A-Z]{2}\\d{6})', 1), ''))
      WHEN funder_id = 4320306076 THEN (NULLIF(regexp_extract(_n, '^(\\d{7})$', 1), ''))
      WHEN funder_id = 4320334764 THEN (NULLIF(regexp_extract(_n, '^(\\d{2}[A-Z]\\d{5}|\\d{8})$', 1), ''))
      WHEN funder_id = 4320320879 THEN (NULLIF(regexp_extract(_n, '^(\\d{9})$', 1), ''))
      WHEN funder_id = 4320322795 THEN (NULLIF(regexp_replace(regexp_replace(_n,'^(MOST|NSC|NSTC)[ -]*',''),'[ -]',''),''))
      WHEN funder_id = 4320320997 THEN (CASE WHEN NULLIF(regexp_extract(_n, '^(\\d{2})/(\\d{5})-(\\d)$', 1), '') IS NOT NULL THEN CONCAT(regexp_extract(_n,'^(\\d{2})/(\\d{5})-(\\d)$',1),'/',regexp_extract(_n,'^(\\d{2})/(\\d{5})-(\\d)$',2),'-',regexp_extract(_n,'^(\\d{2})/(\\d{5})-(\\d)$',3)) END)
      WHEN funder_id = 4320334779 THEN (NULLIF(regexp_replace(_n,' ',''),''))
      WHEN funder_id = 4320320300 THEN (NULLIF(regexp_extract(_n, '^(\\d{6}|\\d{9})$', 1), ''))
      WHEN funder_id = 4320334593 THEN (CASE WHEN _n rlike '^\\d{1,6}-\\d{4}$' THEN CONCAT(regexp_extract(_n,'-(\\d{4})$',1),'-',CAST(CAST(regexp_extract(_n,'^(\\d{1,6})-',1) AS BIGINT) AS STRING)) WHEN _n rlike '^[A-Z]+-\\d{4}-\\d{4,6}$' THEN CONCAT(regexp_extract(_n,'-(\\d{4})-',1),'-',CAST(CAST(regexp_extract(_n,'-(\\d{4,6})$',1) AS BIGINT) AS STRING)) END)
      WHEN funder_id = 4320320883 THEN (CASE WHEN NULLIF(regexp_extract(_n, '^ANR-(\\d{2})-([A-Z0-9]{2,6})-(\\d{4})', 1), '') IS NOT NULL THEN CONCAT(regexp_extract(_n,'^ANR-(\\d{2})-([A-Z0-9]{2,6})-(\\d{4})',1),'-',regexp_extract(_n,'^ANR-(\\d{2})-([A-Z0-9]{2,6})-(\\d{4})',2),'-',regexp_extract(_n,'^ANR-(\\d{2})-([A-Z0-9]{2,6})-(\\d{4})',3)) END)
      WHEN funder_id = 4320320924 THEN (CAST(CAST(NULLIF(regexp_extract(_n, '^(\\d{1,6})$', 1), '') AS BIGINT) AS STRING))
      WHEN funder_id = 4320311904 THEN (LPAD(COALESCE(NULLIF(regexp_extract(_n, '360G-WELLCOME-(\\d{5,6})', 1), ''), NULLIF(regexp_extract(_n, '^(\\d{5,6})(?:[/_ ][A-Z](?:[/_ ]\\d{2})?([/_ ][A-Z])?)?$', 1), '')),6,'0'))
      WHEN funder_id = 4320334627 THEN (NULLIF(regexp_replace(_n,' ',''),''))
      WHEN funder_id = 2461203286 THEN (NULLIF(regexp_replace(regexp_replace(_n,'^(MOST|NSC|NSTC)[ -]*',''),'[ -]',''),''))
      WHEN funder_id = 4320334506 THEN (CAST(CAST(NULLIF(regexp_extract(_n, '^(\\d{4,6})_\\d+$', 1), '') AS BIGINT) AS STRING))
      WHEN funder_id = 4320306230 THEN (NULLIF(regexp_replace(_n,' ',''),''))
      WHEN funder_id = 4320321091 THEN (NULLIF(regexp_extract(regexp_replace(_n,' ',''),'^(8888\\d\\.\\d{6}/\\d{4}-\\d{2})$', 1), ''))
      WHEN funder_id = 4320306085 THEN (NULLIF(regexp_extract(regexp_replace(_n,'[ -]',''),'^([A-Z][A-Z0-9]{4}\\d{6}|\\d{2}[A-Z][A-Z0-9]\\d{4,5})$', 1), ''))
    END
  ELSE
    CASE
      WHEN funder_id = 4320321001 THEN (NULLIF(regexp_extract(_n, '(?<!\\d)(\\d{8})(?!\\d)', 1), ''))
      WHEN funder_id = 4320332161 THEN (CASE WHEN NULLIF(regexp_extract(_n, '([A-Z]{2}) ?-?(\\d{5,6})(?!\\d)', 1), '') IS NOT NULL THEN CONCAT(regexp_extract(_n,'([A-Z]{2}) ?-?(\\d{5,6})(?!\\d)',1), LPAD(regexp_extract(_n,'([A-Z]{2}) ?-?(\\d{5,6})(?!\\d)',2),6,'0')) END)
      WHEN funder_id = 4320306076 THEN (NULLIF(regexp_extract(_n, '(?<!\\d)(\\d{7})(?!\\d)', 1), ''))
      WHEN funder_id = 4320334764 THEN (NULLIF(regexp_extract(_n, '^(?:KAKENHI|JP|NO\\.?|GRANT)?[ -]*(\\d{2}[A-Z]\\d{5}|\\d{8})$', 1), ''))
      WHEN funder_id = 4320320879 THEN (NULLIF(regexp_extract(_n, '(?<!\\d)(\\d{9})(?!\\d)', 1), ''))
      WHEN funder_id = 4320322795 THEN (NULLIF(regexp_replace(regexp_replace(_n,'^(MOST|NSC|NSTC)[ -]*',''),'[ -]',''),''))
      WHEN funder_id = 4320320997 THEN (CASE WHEN NULLIF(regexp_extract(_n, '(?<!\\d)(\\d{2,4})/(\\d{4,5})-(\\d)(?!\\d)', 1), '') IS NOT NULL THEN CONCAT(RIGHT(regexp_extract(_n,'(?<!\\d)(\\d{2,4})/(\\d{4,5})-(\\d)(?!\\d)',1),2),'/',LPAD(regexp_extract(_n,'(?<!\\d)(\\d{2,4})/(\\d{4,5})-(\\d)(?!\\d)',2),5,'0'),'-',regexp_extract(_n,'(?<!\\d)(\\d{2,4})/(\\d{4,5})-(\\d)(?!\\d)',3)) END)
      WHEN funder_id = 4320334779 THEN (NULLIF(regexp_replace(_n,' ',''),''))
      WHEN funder_id = 4320320300 THEN (COALESCE(NULLIF(regexp_extract(_n, '(?<!\\d)(101\\d{6})(?!\\d)', 1), ''), NULLIF(regexp_extract(_n, '(?<!\\d)(\\d{6})(?!\\d)', 1), '')))
      WHEN funder_id = 4320334593 THEN (CASE WHEN regexp_replace(_n,' ','') rlike '[A-Z]{3,7}/?-?\\d{4}-?\\d{4,6}$' THEN CONCAT(regexp_extract(regexp_replace(_n,' ',''),'(\\d{4})-?\\d{4,6}$',1),'-',CAST(CAST(regexp_extract(regexp_replace(_n,' ',''),'(\\d{4,6})$',1) AS BIGINT) AS STRING)) WHEN _n rlike '^\\d{5,6}[ -]\\d{4}$' THEN CONCAT(regexp_extract(_n,'(\\d{4})$',1),'-',CAST(CAST(regexp_extract(_n,'^(\\d{5,6})',1) AS BIGINT) AS STRING)) END)
      WHEN funder_id = 4320320883 THEN (CASE WHEN NULLIF(regexp_extract(regexp_replace(_n,' ',''),'(?:ANR-?)?(\\d{2})-([A-Z0-9]{2,6})-(\\d{4})',1),'') IS NOT NULL THEN CONCAT(regexp_extract(regexp_replace(_n,' ',''),'(?:ANR-?)?(\\d{2})-([A-Z0-9]{2,6})-(\\d{4})',1),'-',regexp_extract(regexp_replace(_n,' ',''),'(?:ANR-?)?(\\d{2})-([A-Z0-9]{2,6})-(\\d{4})',2),'-',regexp_extract(regexp_replace(_n,' ',''),'(?:ANR-?)?(\\d{2})-([A-Z0-9]{2,6})-(\\d{4})',3)) END)
      WHEN funder_id = 4320320924 THEN (CAST(CAST(CASE WHEN _n rlike '^\\d{12}$' THEN SUBSTR(_n,7) ELSE NULLIF(regexp_extract(_n, '(\\d{5,6})$', 1), '') END AS BIGINT) AS STRING))
      WHEN funder_id = 4320311904 THEN (LPAD(NULLIF(regexp_extract(_n, '^(\\d{5,6})(?:[/_ ][A-Z](?:[/_ ]\\d{2})?([/_ ][A-Z])?)?$', 1), ''),6,'0'))
      WHEN funder_id = 4320334627 THEN (NULLIF(regexp_replace(_n,' ',''),''))
      WHEN funder_id = 2461203286 THEN (NULLIF(regexp_replace(regexp_replace(_n,'^(MOST|NSC|NSTC)[ -]*',''),'[ -]',''),''))
      WHEN funder_id = 4320334506 THEN (CAST(CAST(NULLIF(regexp_extract(regexp_replace(regexp_replace(_n,'^[#]+ ?',''),'^(950[- ]|[A-Z]{2,4}[- ]?)',''),'^(\\d{4,6})([-_]\\d+)?$',1),'') AS BIGINT) AS STRING))
      WHEN funder_id = 4320306230 THEN (NULLIF(regexp_replace(_n,' ',''),''))
      WHEN funder_id = 4320321091 THEN (NULLIF(regexp_extract(regexp_replace(_n,' ',''),'(8888\\d\\.\\d{6}/\\d{4}-\\d{2})', 1), ''))
      WHEN funder_id = 4320306085 THEN (NULLIF(regexp_extract(regexp_replace(_n,'[ -]',''),'([A-Z][A-Z0-9]{4}\\d{6}|(?<!\\d)\\d{2}[A-Z][A-Z0-9]\\d{4,5}(?!\\d))', 1), ''))
    END
  END,
  CASE WHEN award_id IS NULL THEN NULL WHEN LENGTH(REGEXP_REPLACE(LOWER(award_id), '[^a-z0-9]', '')) >= 4 THEN REGEXP_REPLACE(LOWER(award_id), '[^a-z0-9]', '') ELSE LOWER(TRIM(award_id)) END
) FROM _t;

-- Verdict per deposited id (feeds the junk guard; read-only w.r.t. awards flow):
--   confirmed           key uniquely hits the funder's registry
--   confirmed_ambiguous key hits >1 registry award (renewal-year families)
--   plausible           fits the funder's id grammar, no registry hit
--   garbage             neither (salvage chain runs before any suppression)
-- Unconfigured funders get verdict 'unscored'.
CREATE OR REPLACE TABLE openalex.awards.award_id_verdicts
USING delta
AS
WITH dep AS (
  -- Deposited ids from the PRE-GUARD junction tables (see JUNCTIONS note in
  -- the generator) plus legacy crossref provenances that have no junction.
  SELECT DISTINCT funder_id, funder_award_id FROM (
    SELECT funder_id, aid AS funder_award_id
    FROM openalex.awards.crossref_work_funders LATERAL VIEW EXPLODE(award_ids) AS aid
    UNION ALL
    SELECT funder_id, aid AS funder_award_id
    FROM openalex.awards.europepmc_work_funders LATERAL VIEW EXPLODE(award_ids) AS aid
    UNION ALL
    SELECT funder_id, aid AS funder_award_id
    FROM openalex.awards.datacite_work_funders LATERAL VIEW EXPLODE(award_ids) AS aid
    UNION ALL
    -- 4th guarded door: CreateBackfillAwards ('crossref_work.grants'); its
    -- pre-guard source is the backfill_awards intermediate (already exploded)
    SELECT funder_id, funder_award_id
    FROM openalex.awards.backfill_awards
    UNION ALL
    -- legacy crossref provenance (scored, not guarded — no pre-guard table)
    SELECT funder_id, funder_award_id
    FROM openalex.awards.openalex_awards_raw
    WHERE provenance IN ('crossref_work') AND funder_award_id IS NOT NULL
  ) WHERE funder_award_id IS NOT NULL
),
-- TWO-KEY registry check, mirroring the CreateAwards alias/collapse machinery
-- exactly (canonical_g on the pure generic key + canonical_s on the sharp
-- COALESCE key). Checking only the COALESCE key under-detects: an id whose
-- sharp extraction fires but misses the registry can still collapse via its
-- generic key — scoring it 'garbage' would suppress ids the fold merges today
-- (2,848 such ids caught by the collapse-safety gate, 2026-08-03).
reg AS (
  SELECT funder_id, openalex.awards.award_norm_key(funder_id, funder_award_id, 'registry') AS nk,
         COUNT(DISTINCT id) AS n_awards
  FROM openalex.awards.openalex_awards_raw
  WHERE priority >= 3 AND funder_award_id IS NOT NULL
  GROUP BY 1, 2
),
reg_g AS (
  SELECT funder_id, CASE WHEN funder_award_id IS NULL THEN NULL WHEN LENGTH(REGEXP_REPLACE(LOWER(funder_award_id), '[^a-z0-9]', '')) >= 4 THEN REGEXP_REPLACE(LOWER(funder_award_id), '[^a-z0-9]', '') ELSE LOWER(TRIM(funder_award_id)) END AS nk_g,
         COUNT(DISTINCT id) AS n_awards
  FROM openalex.awards.openalex_awards_raw
  WHERE priority >= 3 AND funder_award_id IS NOT NULL
  GROUP BY 1, 2
),
keyed AS (
  SELECT funder_id, funder_award_id, _n,
    openalex.awards.award_norm_key(funder_id, funder_award_id, 'deposited') AS nk,
    CASE WHEN funder_award_id IS NULL THEN NULL WHEN LENGTH(REGEXP_REPLACE(LOWER(funder_award_id), '[^a-z0-9]', '')) >= 4 THEN REGEXP_REPLACE(LOWER(funder_award_id), '[^a-z0-9]', '') ELSE LOWER(TRIM(funder_award_id)) END AS nk_g
  FROM (SELECT funder_id, funder_award_id,
          regexp_replace(regexp_replace(regexp_replace(UPPER(TRIM(funder_award_id)), '[\\u2010-\\u2015\\u2212\\uFE58\\uFE63\\uFF0D]', '-'), '[\\u00A0\\u1680\\u2000-\\u200B\\u202F\\u205F\\u3000]', ' '), '  +', ' ') AS _n
        FROM dep)
),
scored AS (
  SELECT k.funder_id, k.funder_award_id, k._n, k.nk,
    COALESCE(r.n_awards, rg.n_awards) AS n_awards,
    CASE
      WHEN k.funder_id = 4320321001 THEN (k._n rlike '(?<!\\d)\\d{8}(?!\\d)')
      WHEN k.funder_id = 4320332161 THEN (k._n rlike '[A-Z]\\d{2} ?-?[A-Z]{2} ?-?\\d{5,6}' or k._n rlike '^[A-Z]{2} ?-?\\d{5,6}')
      WHEN k.funder_id = 4320306076 THEN (k._n rlike '^([A-Z]{2,5}[ -]?)?\\d{7}$')
      WHEN k.funder_id = 4320334764 THEN (k._n rlike '^(KAKENHI|JP|NO\\.?|GRANT)?[ -]*(\\d{2}[A-Z]\\d{5}|\\d{8})$')
      WHEN k.funder_id = 4320320879 THEN (k._n rlike '^(SFB|TRR|CRC|EXC|GRK|RTG|FOR|SPP|INST|NFDI|KFO|FZT) ?/?-?\\d+' or k._n rlike '^(DFG[ -])?[A-Z]{1,4} ?\\d{2,4}(/\\d+)?(-\\d+)?( .*)?$' or k._n rlike '(?<!\\d)\\d{9}(?!\\d)')
      WHEN k.funder_id = 4320322795 THEN (regexp_replace(regexp_replace(k._n,'^(MOST|NSC|NSTC)[ -]*',''),'[ -]','') rlike '^\\d{6,7}[A-Z]\\d{6}(MY\\d)?E?\\d?$')
      WHEN k.funder_id = 4320320997 THEN (k._n rlike '(?<!\\d)\\d{2,4}/\\d{4,5}-\\d(?!\\d)')
      WHEN k.funder_id = 4320334779 THEN (k._n rlike '^[A-Z0-9 ./-]+$' and (k._n rlike '/' or k._n rlike '^\\d{4}\\.\\d{5}\\.'))
      WHEN k.funder_id = 4320320300 THEN (k._n rlike '^(GA ?N?°? ?)?\\d{6}$' or k._n rlike '^101\\d{6}$' or k._n rlike '-CT-\\d{4}-' or k._n rlike '(FP[567]|H2020|HORIZON|MSCA|ERC|GA) ?N?°? ?-?\\d{6}')
      WHEN k.funder_id = 4320334593 THEN (k._n rlike '^[A-Z]{3,7}[ /-]?\\d{4}[ -]?\\d{4,6}$' or k._n rlike '^[A-Z]{3,7}[ -]?\\d{4,6}([ -]?\\d{2,4})?$' or k._n rlike '^\\d{5,6}([ -]?\\d{2,4})?$')
      WHEN k.funder_id = 4320320883 THEN (regexp_replace(k._n,' ','') rlike '(ANR-?)?\\d{2}-[A-Z0-9]{2,6}-\\d{4}')
      WHEN k.funder_id = 4320320924 THEN (k._n rlike '^[0-9A-Z]{0,8}[_-]?\\d{4,6}$' or k._n rlike '^\\d{12}$')
      WHEN k.funder_id = 4320311904 THEN (k._n rlike '^\\d{5,6}([/_ ][A-Z][/_ ]\\d{2}[/_ ][A-Z])?$')
      WHEN k.funder_id = 4320334627 THEN (regexp_replace(k._n,' ','') rlike '^EP/[A-Z0-9]{6,7}/[0-9]$' or k._n rlike '^\\d{7}$')
      WHEN k.funder_id = 2461203286 THEN (regexp_replace(regexp_replace(k._n,'^(MOST|NSC|NSTC)[ -]*',''),'[ -]','') rlike '^\\d{6,7}[A-Z]\\d{6}(MY\\d)?E?\\d?$')
      WHEN k.funder_id = 4320334506 THEN (k._n rlike '^#? ?(950[- ])?([A-Z]{2,4}[- ]?)?\\d{4,6}([-_]\\d+)?$')
      WHEN k.funder_id = 4320306230 THEN (regexp_replace(k._n,' ','') rlike '^\\d{2}[A-Z]{2,10}\\d{4,9}$' or k._n rlike '^\\d{6,9}$')
      WHEN k.funder_id = 4320321091 THEN ((regexp_replace(k._n,' ','') rlike '^8888\\d\\.\\d{6}/\\d{4}-\\d{2}$' or regexp_replace(k._n,' ','') rlike '^(BEX|PDSE|PNPD|PROEX|DS|AUX)-?\\d{3,7}([-/.]\\d{1,4}){0,3}$' or k._n rlike '^\\d{1,4}/(19|20)\\d{2}$'))
      WHEN k.funder_id = 4320306085 THEN (((regexp_replace(k._n,'[ -]','') rlike '^([A-Z][A-Z0-9]{4}\\d{6}|\\d{2}[A-Z][A-Z0-9]\\d{4,5})$' and not regexp_replace(k._n,'[ -]','') rlike '^[A-Z]\\d{2}[A-Z]{2}\\d{5,6}$') or regexp_replace(k._n,'[ -]','') rlike '^(75[A-Z0-9]{9,13}|HHSN[A-Z0-9]{9,15})$'))
    END AS grammar_pass
  FROM keyed k
  LEFT JOIN reg r ON r.funder_id = k.funder_id AND r.nk = k.nk
  LEFT JOIN reg_g rg ON rg.funder_id = k.funder_id AND rg.nk_g = k.nk_g
)
SELECT funder_id, funder_award_id, nk, n_awards,
  CASE
    WHEN funder_id NOT IN (4320321001,4320332161,4320306076,4320334764,4320320879,4320322795,4320320997,4320334779,4320320300,4320334593,4320320883,4320320924,4320311904,4320334627,2461203286,4320334506,4320306230,4320321091,4320306085) THEN 'unscored'
    -- review F3: weak surface-form is checked FIRST — a bare number is weak
    -- evidence regardless of how many registry awards it happens to hit
    WHEN n_awards >= 1 AND ((funder_id = 4320334506 AND _n rlike '^[0-9]{4,6}$') OR (funder_id = 4320311904 AND _n rlike '^[0-9]{5,6}$') OR (funder_id = 4320320924 AND _n rlike '^[0-9]{4,6}$') OR (funder_id = 4320320300 AND _n rlike '^[0-9]{6}$') OR (funder_id = 4320306076 AND _n rlike '^[0-9]{7}$') OR (funder_id = 4320334593 AND _n rlike '^[0-9]{4,6}$')) THEN 'confirmed_weak'
    WHEN n_awards = 1 THEN 'confirmed'
    WHEN n_awards > 1 THEN 'confirmed_ambiguous'
    WHEN grammar_pass THEN 'plausible'
    ELSE 'garbage'
  END AS verdict,
  current_timestamp() AS scored_date
FROM scored;

-- ============================================================================
-- Salvage chain (#690 guard, 2026-08-03 priority 1). Runs over garbage-verdict
-- ids BEFORE any suppression. Three rescue steps:
--   decorated_own_id  generic decoration strip -> re-key -> own-registry hit
--                     (suffix _weak when the stripped form is a bare number at
--                     a WEAK_BARE funder: minted but never merge material;
--                     decorated_plausible when the stripped form only passes
--                     the funder's grammar — parity with S2 plausible parts)
--   multi_id_split    concatenated ids ("A123, B456"): split, score each part;
--                     rescued when any part confirms or is plausible
--   wrong_funder      DETECTION ONLY (re-link write = #624's): letter-bearing
--                     ids that pass another funder's STRONG cross-grammar
--                     (XGRAM: distinctive funder tokens only) AND hit that
--                     funder's registry. Bare numerics are excluded by
--                     construction (the 2026-08-03 foreign-numeric control
--                     measured 15-40% coincidental hits on dense-numeric
--                     registries), which also makes WEAK_BARE unreachable here.
-- A salvage row exempts the id from suppression; it never changes minting or
-- merging by itself.
-- ============================================================================
CREATE OR REPLACE TABLE openalex.awards.award_id_salvage
USING delta
AS
WITH reg AS (
  SELECT funder_id, nk, COUNT(DISTINCT id) AS n_awards FROM (
    SELECT funder_id, id,
      openalex.awards.award_norm_key(funder_id, funder_award_id, 'registry') AS nk
    FROM openalex.awards.openalex_awards_raw
    WHERE priority >= 3 AND funder_award_id IS NOT NULL
  ) WHERE nk IS NOT NULL GROUP BY 1, 2
),
-- generic-key registry arm: S1/S2 rescue checks BOTH keys, mirroring the
-- two-key alias/collapse machinery (same reasoning as in award_id_verdicts)
reg_g AS (
  SELECT funder_id, CASE WHEN funder_award_id IS NULL THEN NULL WHEN LENGTH(REGEXP_REPLACE(LOWER(funder_award_id), '[^a-z0-9]', '')) >= 4 THEN REGEXP_REPLACE(LOWER(funder_award_id), '[^a-z0-9]', '') ELSE LOWER(TRIM(funder_award_id)) END AS nk_g,
         COUNT(DISTINCT id) AS n_awards
  FROM openalex.awards.openalex_awards_raw
  WHERE priority >= 3 AND funder_award_id IS NOT NULL
  GROUP BY 1, 2
),
garbage AS (
  SELECT funder_id, funder_award_id,
    regexp_replace(regexp_replace(regexp_replace(UPPER(TRIM(funder_award_id)), '[\\u2010-\\u2015\\u2212\\uFE58\\uFE63\\uFF0D]', '-'), '[\\u00A0\\u1680\\u2000-\\u200B\\u202F\\u205F\\u3000]', ' '), '  +', ' ') AS _n
  FROM openalex.awards.award_id_verdicts WHERE verdict = 'garbage'
),
-- S1: decorated own-id (strip applied lead-then-trail-twice: "12345 (ABC).")
stripped AS (
  SELECT funder_id, funder_award_id, _n,
    regexp_replace(regexp_replace(regexp_replace(_n,
      '^((GRANT|GRANTS|AWARD|AWARDS|PROJECT|CONTRACT|AGREEMENT|APPLICATION|APP|REFERENCE|REF|NUMBER|NUM|NO|N0|ID|CODE|FUNDREF|UNDER|JSPS|KAKENHI|MEXT)[ .:#°-]+|[#№(\\[]+ ?)+', ''), '([ .,;:)\\]]+|[ -]*\\(.*\\))$', ''), '([ .,;:)\\]]+|[ -]*\\(.*\\))$', '') AS s
  FROM garbage
),
s1_keyed AS (
  -- UDFs in projection only (Spark forbids them in JOIN ON / LATERAL VIEW)
  SELECT funder_id, funder_award_id, s,
    openalex.awards.award_norm_key(funder_id, s, 'deposited') AS s_nk,
    CASE WHEN s IS NULL THEN NULL WHEN LENGTH(REGEXP_REPLACE(LOWER(s), '[^a-z0-9]', '')) >= 4 THEN REGEXP_REPLACE(LOWER(s), '[^a-z0-9]', '') ELSE LOWER(TRIM(s)) END AS s_nk_g,
    openalex.awards.award_id_is_weak(funder_id, s) AS s_weak,
    CASE
      WHEN funder_id = 4320321001 THEN (s rlike '(?<!\\d)\\d{8}(?!\\d)')
      WHEN funder_id = 4320332161 THEN (s rlike '[A-Z]\\d{2} ?-?[A-Z]{2} ?-?\\d{5,6}' or s rlike '^[A-Z]{2} ?-?\\d{5,6}')
      WHEN funder_id = 4320306076 THEN (s rlike '^([A-Z]{2,5}[ -]?)?\\d{7}$')
      WHEN funder_id = 4320334764 THEN (s rlike '^(KAKENHI|JP|NO\\.?|GRANT)?[ -]*(\\d{2}[A-Z]\\d{5}|\\d{8})$')
      WHEN funder_id = 4320320879 THEN (s rlike '^(SFB|TRR|CRC|EXC|GRK|RTG|FOR|SPP|INST|NFDI|KFO|FZT) ?/?-?\\d+' or s rlike '^(DFG[ -])?[A-Z]{1,4} ?\\d{2,4}(/\\d+)?(-\\d+)?( .*)?$' or s rlike '(?<!\\d)\\d{9}(?!\\d)')
      WHEN funder_id = 4320322795 THEN (regexp_replace(regexp_replace(s,'^(MOST|NSC|NSTC)[ -]*',''),'[ -]','') rlike '^\\d{6,7}[A-Z]\\d{6}(MY\\d)?E?\\d?$')
      WHEN funder_id = 4320320997 THEN (s rlike '(?<!\\d)\\d{2,4}/\\d{4,5}-\\d(?!\\d)')
      WHEN funder_id = 4320334779 THEN (s rlike '^[A-Z0-9 ./-]+$' and (s rlike '/' or s rlike '^\\d{4}\\.\\d{5}\\.'))
      WHEN funder_id = 4320320300 THEN (s rlike '^(GA ?N?°? ?)?\\d{6}$' or s rlike '^101\\d{6}$' or s rlike '-CT-\\d{4}-' or s rlike '(FP[567]|H2020|HORIZON|MSCA|ERC|GA) ?N?°? ?-?\\d{6}')
      WHEN funder_id = 4320334593 THEN (s rlike '^[A-Z]{3,7}[ /-]?\\d{4}[ -]?\\d{4,6}$' or s rlike '^[A-Z]{3,7}[ -]?\\d{4,6}([ -]?\\d{2,4})?$' or s rlike '^\\d{5,6}([ -]?\\d{2,4})?$')
      WHEN funder_id = 4320320883 THEN (regexp_replace(s,' ','') rlike '(ANR-?)?\\d{2}-[A-Z0-9]{2,6}-\\d{4}')
      WHEN funder_id = 4320320924 THEN (s rlike '^[0-9A-Z]{0,8}[_-]?\\d{4,6}$' or s rlike '^\\d{12}$')
      WHEN funder_id = 4320311904 THEN (s rlike '^\\d{5,6}([/_ ][A-Z][/_ ]\\d{2}[/_ ][A-Z])?$')
      WHEN funder_id = 4320334627 THEN (regexp_replace(s,' ','') rlike '^EP/[A-Z0-9]{6,7}/[0-9]$' or s rlike '^\\d{7}$')
      WHEN funder_id = 2461203286 THEN (regexp_replace(regexp_replace(s,'^(MOST|NSC|NSTC)[ -]*',''),'[ -]','') rlike '^\\d{6,7}[A-Z]\\d{6}(MY\\d)?E?\\d?$')
      WHEN funder_id = 4320334506 THEN (s rlike '^#? ?(950[- ])?([A-Z]{2,4}[- ]?)?\\d{4,6}([-_]\\d+)?$')
      WHEN funder_id = 4320306230 THEN (regexp_replace(s,' ','') rlike '^\\d{2}[A-Z]{2,10}\\d{4,9}$' or s rlike '^\\d{6,9}$')
      WHEN funder_id = 4320321091 THEN ((regexp_replace(s,' ','') rlike '^8888\\d\\.\\d{6}/\\d{4}-\\d{2}$' or regexp_replace(s,' ','') rlike '^(BEX|PDSE|PNPD|PROEX|DS|AUX)-?\\d{3,7}([-/.]\\d{1,4}){0,3}$' or s rlike '^\\d{1,4}/(19|20)\\d{2}$'))
      WHEN funder_id = 4320306085 THEN (((regexp_replace(s,'[ -]','') rlike '^([A-Z][A-Z0-9]{4}\\d{6}|\\d{2}[A-Z][A-Z0-9]\\d{4,5})$' and not regexp_replace(s,'[ -]','') rlike '^[A-Z]\\d{2}[A-Z]{2}\\d{5,6}$') or regexp_replace(s,'[ -]','') rlike '^(75[A-Z0-9]{9,13}|HHSN[A-Z0-9]{9,15})$'))
    END AS s_gram
  FROM stripped WHERE s <> '' AND s <> _n
),
s1 AS (
  -- rescue on registry hit (either key), or — parity with S2's plausible
  -- parts — on the stripped form passing the funder's own grammar
  -- ("# 88887.684374/2022-00" at a funder whose registry can't confirm it)
  SELECT k.funder_id, k.funder_award_id,
    CASE WHEN COALESCE(r.nk, rg.nk_g) IS NULL THEN 'decorated_plausible'
         WHEN k.s_weak THEN 'decorated_own_id_weak'
         ELSE 'decorated_own_id' END AS action,
    k.funder_id AS target_funder_id,
    COALESCE(r.nk, rg.nk_g) AS target_nk,
    COALESCE(r.n_awards, rg.n_awards) AS n_awards,
    k.s AS detail
  FROM s1_keyed k
  LEFT JOIN reg r ON r.funder_id = k.funder_id AND r.nk = k.s_nk
  LEFT JOIN reg_g rg ON rg.funder_id = k.funder_id AND rg.nk_g = k.s_nk_g
  WHERE COALESCE(r.nk, rg.nk_g) IS NOT NULL OR (k.s_gram AND NOT k.s_weak)
),
-- S2: multi-id concat split
multi AS (
  SELECT funder_id, funder_award_id, _n FROM garbage
  WHERE ((_n rlike '[,;&]') OR (_n rlike ' AND ') OR (_n rlike ' \\+ ')) AND _n rlike '[0-9]{3}'
),
parts0 AS (
  SELECT funder_id, funder_award_id, TRIM(p) AS p0
  FROM multi LATERAL VIEW EXPLODE(split(_n, '[,;&+]|\\bAND\\b')) AS p
),
parts AS (
  SELECT funder_id, funder_award_id,
    regexp_replace(regexp_replace(regexp_replace(p0,
      '^((GRANT|GRANTS|AWARD|AWARDS|PROJECT|CONTRACT|AGREEMENT|APPLICATION|APP|REFERENCE|REF|NUMBER|NUM|NO|N0|ID|CODE|FUNDREF|UNDER|JSPS|KAKENHI|MEXT)[ .:#°-]+|[#№(\\[]+ ?)+', ''), '([ .,;:)\\]]+|[ -]*\\(.*\\))$', ''), '([ .,;:)\\]]+|[ -]*\\(.*\\))$', '') AS part
  FROM parts0 WHERE p0 <> ''
),
parts_keyed AS (
  SELECT funder_id, funder_award_id, part,
    openalex.awards.award_norm_key(funder_id, part, 'deposited') AS p_nk,
    CASE WHEN part IS NULL THEN NULL WHEN LENGTH(REGEXP_REPLACE(LOWER(part), '[^a-z0-9]', '')) >= 4 THEN REGEXP_REPLACE(LOWER(part), '[^a-z0-9]', '') ELSE LOWER(TRIM(part)) END AS p_nk_g,
    openalex.awards.award_id_is_weak(funder_id, part) AS p_weak,
    CASE
      WHEN funder_id = 4320321001 THEN (part rlike '(?<!\\d)\\d{8}(?!\\d)')
      WHEN funder_id = 4320332161 THEN (part rlike '[A-Z]\\d{2} ?-?[A-Z]{2} ?-?\\d{5,6}' or part rlike '^[A-Z]{2} ?-?\\d{5,6}')
      WHEN funder_id = 4320306076 THEN (part rlike '^([A-Z]{2,5}[ -]?)?\\d{7}$')
      WHEN funder_id = 4320334764 THEN (part rlike '^(KAKENHI|JP|NO\\.?|GRANT)?[ -]*(\\d{2}[A-Z]\\d{5}|\\d{8})$')
      WHEN funder_id = 4320320879 THEN (part rlike '^(SFB|TRR|CRC|EXC|GRK|RTG|FOR|SPP|INST|NFDI|KFO|FZT) ?/?-?\\d+' or part rlike '^(DFG[ -])?[A-Z]{1,4} ?\\d{2,4}(/\\d+)?(-\\d+)?( .*)?$' or part rlike '(?<!\\d)\\d{9}(?!\\d)')
      WHEN funder_id = 4320322795 THEN (regexp_replace(regexp_replace(part,'^(MOST|NSC|NSTC)[ -]*',''),'[ -]','') rlike '^\\d{6,7}[A-Z]\\d{6}(MY\\d)?E?\\d?$')
      WHEN funder_id = 4320320997 THEN (part rlike '(?<!\\d)\\d{2,4}/\\d{4,5}-\\d(?!\\d)')
      WHEN funder_id = 4320334779 THEN (part rlike '^[A-Z0-9 ./-]+$' and (part rlike '/' or part rlike '^\\d{4}\\.\\d{5}\\.'))
      WHEN funder_id = 4320320300 THEN (part rlike '^(GA ?N?°? ?)?\\d{6}$' or part rlike '^101\\d{6}$' or part rlike '-CT-\\d{4}-' or part rlike '(FP[567]|H2020|HORIZON|MSCA|ERC|GA) ?N?°? ?-?\\d{6}')
      WHEN funder_id = 4320334593 THEN (part rlike '^[A-Z]{3,7}[ /-]?\\d{4}[ -]?\\d{4,6}$' or part rlike '^[A-Z]{3,7}[ -]?\\d{4,6}([ -]?\\d{2,4})?$' or part rlike '^\\d{5,6}([ -]?\\d{2,4})?$')
      WHEN funder_id = 4320320883 THEN (regexp_replace(part,' ','') rlike '(ANR-?)?\\d{2}-[A-Z0-9]{2,6}-\\d{4}')
      WHEN funder_id = 4320320924 THEN (part rlike '^[0-9A-Z]{0,8}[_-]?\\d{4,6}$' or part rlike '^\\d{12}$')
      WHEN funder_id = 4320311904 THEN (part rlike '^\\d{5,6}([/_ ][A-Z][/_ ]\\d{2}[/_ ][A-Z])?$')
      WHEN funder_id = 4320334627 THEN (regexp_replace(part,' ','') rlike '^EP/[A-Z0-9]{6,7}/[0-9]$' or part rlike '^\\d{7}$')
      WHEN funder_id = 2461203286 THEN (regexp_replace(regexp_replace(part,'^(MOST|NSC|NSTC)[ -]*',''),'[ -]','') rlike '^\\d{6,7}[A-Z]\\d{6}(MY\\d)?E?\\d?$')
      WHEN funder_id = 4320334506 THEN (part rlike '^#? ?(950[- ])?([A-Z]{2,4}[- ]?)?\\d{4,6}([-_]\\d+)?$')
      WHEN funder_id = 4320306230 THEN (regexp_replace(part,' ','') rlike '^\\d{2}[A-Z]{2,10}\\d{4,9}$' or part rlike '^\\d{6,9}$')
      WHEN funder_id = 4320321091 THEN ((regexp_replace(part,' ','') rlike '^8888\\d\\.\\d{6}/\\d{4}-\\d{2}$' or regexp_replace(part,' ','') rlike '^(BEX|PDSE|PNPD|PROEX|DS|AUX)-?\\d{3,7}([-/.]\\d{1,4}){0,3}$' or part rlike '^\\d{1,4}/(19|20)\\d{2}$'))
      WHEN funder_id = 4320306085 THEN (((regexp_replace(part,'[ -]','') rlike '^([A-Z][A-Z0-9]{4}\\d{6}|\\d{2}[A-Z][A-Z0-9]\\d{4,5})$' and not regexp_replace(part,'[ -]','') rlike '^[A-Z]\\d{2}[A-Z]{2}\\d{5,6}$') or regexp_replace(part,'[ -]','') rlike '^(75[A-Z0-9]{9,13}|HHSN[A-Z0-9]{9,15})$'))
    END AS p_gram
  FROM parts WHERE part <> ''
),
s2_scored AS (
  SELECT p.funder_id, p.funder_award_id,
    COUNT(*) AS n_parts,
    SUM(CASE WHEN COALESCE(r.nk, rg.nk_g) IS NOT NULL AND NOT p.p_weak THEN 1 ELSE 0 END) AS n_confirmed_parts,
    SUM(CASE WHEN COALESCE(r.nk, rg.nk_g) IS NULL AND p.p_gram AND NOT p.p_weak THEN 1 ELSE 0 END) AS n_plausible_parts
  FROM parts_keyed p
  LEFT JOIN reg r ON r.funder_id = p.funder_id AND r.nk = p.p_nk
  LEFT JOIN reg_g rg ON rg.funder_id = p.funder_id AND rg.nk_g = p.p_nk_g
  GROUP BY 1, 2
),
s2 AS (
  SELECT funder_id, funder_award_id, 'multi_id_split' AS action,
    funder_id AS target_funder_id, CAST(NULL AS STRING) AS target_nk,
    n_confirmed_parts AS n_awards,
    CONCAT('parts=', n_parts, ' confirmed=', n_confirmed_parts,
           ' plausible=', n_plausible_parts) AS detail
  FROM s2_scored
  WHERE n_confirmed_parts >= 1 OR n_plausible_parts >= 1
),
-- S3: wrong-funder detection. Letter-bearing ids only (bare numerics excluded
-- by the foreign-numeric control), and the claim requires the target funder's
-- STRONG cross-grammar (XGRAM): funders without a distinctive lettered token
-- structure (NSFC, SNSF) are not cross-targets at all — their generic `gram`
-- fields accept non-self-identifying strings and produced tens of thousands
-- of coincidental hits against dense numeric registries in the first build.
wf0 AS (
  -- candidates: letter-bearing, or the FAPESP numeric chassis (NN/NNNNN-N —
  -- structured punctuation, not a bare number; 2.8k FAPESP ids sat under CAPES)
  SELECT g.funder_id, g.funder_award_id, g._n, t.t_fid
  FROM (SELECT * FROM garbage
        WHERE _n rlike '[A-Z]' OR _n rlike '(?<!\d)\d(2, 4)/\d(4, 5)-\d(?!\d)') g
  CROSS JOIN (SELECT explode(array(4320332161,4320306085,4320306076,4320334764,4320320879,4320322795,2461203286,4320320997,4320321091,4320334779,4320320300,4320334593,4320320883,4320311904,4320334627,4320334506,4320306230)) AS t_fid) t
  WHERE t.t_fid <> g.funder_id
),
wf_keyed AS (
  SELECT funder_id, funder_award_id, t_fid,
    openalex.awards.award_norm_key(t_fid, funder_award_id, 'deposited') AS f_nk,
    CASE
      WHEN t_fid = 4320332161 THEN (_n rlike '(^|[^A-Z0-9])\\d?([A-Z]\\d{2}|[A-Z]{2}\\d)[ -]?[A-Z]{2}[ -]?\\d{5,6}([^0-9]|$)' or _n rlike '(^|[^A-Z0-9])(AA|AG|AI|AR|AT|CA|DA|DC|DE|DK|EB|ES|EY|GM|HD|HG|HL|LM|MD|MH|NR|NS|OD|RR|TR|TW)[ -]?\\d{6}([^0-9]|$)' or _n rlike '^(AA|AG|AI|AR|AT|DA|DC|DE|DK|EB|ES|EY|GM|HD|HG|HL|LM|MD|MH|NR|NS|OD|RR|TR|TW)[ -]?\\d{5}$')
      WHEN t_fid = 4320306085 THEN ((regexp_replace(_n,'[ -]','') rlike '^[A-Z][A-Z0-9]{4}\\d{6}$' and not regexp_replace(_n,'[ -]','') rlike '^[A-Z]\\d{2}[A-Z]{2}\\d{5,6}$'))
      WHEN t_fid = 4320306076 THEN (_n rlike '^[A-Z]{2,5}[ -]\\d{7}$')
      WHEN t_fid = 4320334764 THEN (_n rlike '^(KAKENHI|JP)[ -]*(\\d{2}[A-Z]\\d{5}|\\d{8})$' or _n rlike '^\\d{2}[A-Z]\\d{5}$')
      WHEN t_fid = 4320320879 THEN (_n rlike '^(SFB|TRR|CRC|EXC|GRK|RTG|FOR|SPP|INST|NFDI|KFO|FZT) ?/?-?\\d+')
      WHEN t_fid = 4320322795 THEN (regexp_replace(regexp_replace(_n,'^(MOST|NSC|NSTC)[ -]*',''),'[ -]','') rlike '^\\d{6,7}[A-Z]\\d{6}(MY\\d)?E?\\d?$')
      WHEN t_fid = 2461203286 THEN (regexp_replace(regexp_replace(_n,'^(MOST|NSC|NSTC)[ -]*',''),'[ -]','') rlike '^\\d{6,7}[A-Z]\\d{6}(MY\\d)?E?\\d?$')
      WHEN t_fid = 4320320997 THEN (_n rlike '(?<!\\d)\\d{2,4}/\\d{4,5}-\\d(?!\\d)')
      WHEN t_fid = 4320321091 THEN (regexp_replace(_n,' ','') rlike '^8888\\d\\.\\d{6}/\\d{4}-\\d{2}$')
      WHEN t_fid = 4320334779 THEN (_n rlike '^[A-Z0-9 ./-]+$' and _n rlike '[A-Z]' and _n rlike '/')
      WHEN t_fid = 4320320300 THEN (_n rlike '-CT-\\d{4}-' or _n rlike '(FP[567]|H2020|HORIZON|MSCA|ERC|GA) ?N?°? ?-?\\d{6}')
      WHEN t_fid = 4320334593 THEN (_n rlike '^(RGPIN|RGPAS|RGPNS|DGECR|CRDPJ|SAPIN)[ -/]?\\d{4}[ -]?\\d{4,6}$')
      WHEN t_fid = 4320320883 THEN (regexp_replace(_n,' ','') rlike '(ANR-?)?\\d{2}-[A-Z0-9]{2,6}-\\d{4}')
      WHEN t_fid = 4320311904 THEN (_n rlike '^\\d{5,6}[/_ ][A-Z][/_ ]\\d{2}[/_ ][A-Z]$')
      WHEN t_fid = 4320334627 THEN (regexp_replace(_n,' ','') rlike '^EP/[A-Z0-9]{6,7}/[0-9]$')
      WHEN t_fid = 4320334506 THEN (_n rlike '^#? ?(950|MOP|PJT|FDN|FRN|CIHR)[- ]?\\d{4,6}([-_]\\d+)?$')
      WHEN t_fid = 4320306230 THEN (regexp_replace(_n,' ','') rlike '^\\d{2}[A-Z]{2,10}\\d{4,9}$')
    END AS f_gram
  FROM wf0
),
s3 AS (
  SELECT k.funder_id, k.funder_award_id, 'wrong_funder' AS action,
    k.t_fid AS target_funder_id, r.nk AS target_nk, r.n_awards,
    CAST(NULL AS STRING) AS detail
  FROM (SELECT * FROM wf_keyed WHERE f_gram) k
  JOIN reg r ON r.funder_id = k.t_fid AND r.nk = k.f_nk
)
SELECT funder_id, funder_award_id, action, target_funder_id, target_nk,
       n_awards AS n_registry_awards, detail,
       current_timestamp() AS created_date
FROM (SELECT * FROM s1 UNION ALL SELECT * FROM s2 UNION ALL SELECT * FROM s3);

-- ============================================================================
-- Guard decision table — the single checkpoint the four covered ingest doors
-- (CreateCrossrefWorkFunders / CreateEuropePmcWorkFunders /
-- CreateDataCiteWorkFunders / CreateBackfillAwards) consume at mint time.
-- One row per scored (funder_id, funder_award_id). suppress = garbage with no
-- salvage rescue. Ids ABSENT from this table (new since the last scoring run)
-- mint fail-open.
-- ============================================================================
CREATE OR REPLACE TABLE openalex.awards.award_id_guard
USING delta
AS
SELECT v.funder_id, v.funder_award_id, v.verdict,
  CASE WHEN v.verdict = 'garbage' AND s.actions IS NULL
       THEN 'suppress' ELSE 'mint' END AS decision,
  CASE WHEN v.verdict <> 'garbage' THEN v.verdict
       WHEN s.actions IS NOT NULL THEN CONCAT('salvaged:', s.actions)
       ELSE 'garbage_unsalvaged' END AS reason,
  current_timestamp() AS created_date
FROM openalex.awards.award_id_verdicts v
LEFT JOIN (
  SELECT funder_id, funder_award_id,
         array_join(array_sort(collect_set(action)), '+') AS actions
  FROM openalex.awards.award_id_salvage GROUP BY 1, 2
) s ON s.funder_id = v.funder_id AND s.funder_award_id = v.funder_award_id;
