-- GENERATED by scripts/gen_award_norm_key.py — DO NOT EDIT BY HAND.
-- Per-funder award-id translation key (oxjob #690), layered on the 2026-07-31
-- award-id-audit generic key. MERGE_FAMILIES=false.

CREATE OR REPLACE FUNCTION openalex.awards.award_norm_key(funder_id BIGINT, award_id STRING, side STRING)
RETURNS STRING
RETURN
WITH _t AS (SELECT regexp_replace(regexp_replace(regexp_replace(UPPER(TRIM(award_id)), '[\\u2010-\\u2015\\u2212\\uFE58\\uFE63\\uFF0D]', '-'), '[\\u00A0\\u1680\\u2000-\\u200B\\u202F\\u205F\\u3000]', ' '), '  +', ' ') AS _n)
SELECT COALESCE(
  CASE WHEN side = 'registry' THEN
    CASE
      WHEN funder_id = 4320321001 THEN (NULLIF(regexp_extract(_n, '^(\\d{8})$', 1), ''))
      WHEN funder_id = 4320332161 THEN (NULLIF(regexp_extract(_n, '([A-Z]{2}\\d{6})', 1), ''))
      WHEN funder_id = 4320306076 THEN (NULLIF(regexp_extract(_n, '^(\\d{7})$', 1), ''))
      WHEN funder_id = 4320334764 THEN (NULLIF(regexp_extract(_n, '^(\\d{2}[A-Z]\\d{5}|\\d{8})$', 1), ''))
      WHEN funder_id = 4320320879 THEN (NULLIF(regexp_extract(_n, '^(\\d{9})$', 1), ''))
      WHEN funder_id = 4320322795 THEN (NULLIF(regexp_replace(regexp_replace(_n,'^(MOST|NSC|NSTC)[ -]*',''),'[ -]',''),''))
      WHEN funder_id = 4320320997 THEN (CASE WHEN NULLIF(regexp_extract(_n, '^(\\d{2})/(\\d{5})-(\\d)$', 1), '') IS NOT NULL THEN CONCAT(regexp_extract(_n,'^(\\d{2})/(\\d{5})-(\\d)$',1),'/',regexp_extract(_n,'^(\\d{2})/(\\d{5})-(\\d)$',2),'-',regexp_extract(_n,'^(\\d{2})/(\\d{5})-(\\d)$',3)) END)
      WHEN funder_id = 4320334779 THEN (NULLIF(regexp_replace(_n,' ',''),''))
      WHEN funder_id = 4320320300 THEN (NULLIF(regexp_extract(_n, '^(\\d{6}|\\d{9})$', 1), ''))
      WHEN funder_id = 4320334593 THEN (CAST(CAST(COALESCE(NULLIF(regexp_extract(_n, '^(\\d{1,6})-\\d{4}$', 1), ''), NULLIF(regexp_extract(_n, '^[A-Z]+-\\d{4}-(\\d{4,6})$', 1), '')) AS BIGINT) AS STRING))
      WHEN funder_id = 4320320883 THEN (CASE WHEN NULLIF(regexp_extract(_n, '^ANR-(\\d{2})-([A-Z0-9]{2,6})-(\\d{4})', 1), '') IS NOT NULL THEN CONCAT(regexp_extract(_n,'^ANR-(\\d{2})-([A-Z0-9]{2,6})-(\\d{4})',1),'-',regexp_extract(_n,'^ANR-(\\d{2})-([A-Z0-9]{2,6})-(\\d{4})',2),'-',regexp_extract(_n,'^ANR-(\\d{2})-([A-Z0-9]{2,6})-(\\d{4})',3)) END)
      WHEN funder_id = 4320320924 THEN (CAST(CAST(NULLIF(regexp_extract(_n, '^(\\d{1,6})$', 1), '') AS BIGINT) AS STRING))
      WHEN funder_id = 4320311904 THEN (LPAD(COALESCE(NULLIF(regexp_extract(_n, '360G-WELLCOME-(\\d{5,6})', 1), ''), NULLIF(regexp_extract(_n, '^(\\d{5,6})(?:[/_ ][A-Z](?:[/_ ]\\d{2})?([/_ ][A-Z])?)?$', 1), '')),6,'0'))
      WHEN funder_id = 4320334627 THEN (NULLIF(regexp_replace(_n,' ',''),''))
      WHEN funder_id = 2461203286 THEN (NULLIF(regexp_replace(regexp_replace(_n,'^(MOST|NSC|NSTC)[ -]*',''),'[ -]',''),''))
      WHEN funder_id = 4320334506 THEN (CAST(CAST(NULLIF(regexp_extract(_n, '^(\\d{4,6})_\\d+$', 1), '') AS BIGINT) AS STRING))
      WHEN funder_id = 4320306230 THEN (NULLIF(regexp_replace(_n,' ',''),''))
    END
  ELSE
    CASE
      WHEN funder_id = 4320321001 THEN (NULLIF(regexp_extract(_n, '(?<!\\d)(\\d{8})(?!\\d)', 1), ''))
      WHEN funder_id = 4320332161 THEN (CASE WHEN NULLIF(regexp_extract(_n, '([A-Z]{2}) ?-?(\\d{5,6})(?!\\d)', 1), '') IS NOT NULL THEN CONCAT(regexp_extract(_n,'([A-Z]{2}) ?-?(\\d{5,6})(?!\\d)',1), LPAD(regexp_extract(_n,'([A-Z]{2}) ?-?(\\d{5,6})(?!\\d)',2),6,'0')) END)
      WHEN funder_id = 4320306076 THEN (NULLIF(regexp_extract(_n, '(?<!\\d)(\\d{7})(?!\\d)', 1), ''))
      WHEN funder_id = 4320334764 THEN (NULLIF(regexp_extract(_n, '^(?:KAKENHI|JP|NO\\.?|GRANT)?[ -]*(\\d{2}[A-Z]\\d{5}|\\d{8})$', 1), ''))
      WHEN funder_id = 4320320879 THEN (NULLIF(regexp_extract(_n, '(?<!\\d)(\\d{9})(?!\\d)', 1), ''))
      WHEN funder_id = 4320322795 THEN (NULLIF(regexp_replace(regexp_replace(_n,'^(MOST|NSC|NSTC)[ -]*',''),'[ -]',''),''))
      WHEN funder_id = 4320320997 THEN (CASE WHEN NULLIF(regexp_extract(_n, '(?<!\\d)(\\d{2,4})/(\\d{4,5})-(\\d)(?!\\d)', 1), '') IS NOT NULL THEN CONCAT(RIGHT(regexp_extract(_n,'(?<!\\d)(\\d{2,4})/(\\d{4,5})-(\\d)(?!\\d)',1),2),'/',LPAD(regexp_extract(_n,'(?<!\\d)(\\d{2,4})/(\\d{4,5})-(\\d)(?!\\d)',2),5,'0'),'-',regexp_extract(_n,'(?<!\\d)(\\d{2,4})/(\\d{4,5})-(\\d)(?!\\d)',3)) END)
      WHEN funder_id = 4320334779 THEN (NULLIF(regexp_replace(_n,' ',''),''))
      WHEN funder_id = 4320320300 THEN (COALESCE(NULLIF(regexp_extract(_n, '(?<!\\d)(101\\d{6})(?!\\d)', 1), ''), NULLIF(regexp_extract(_n, '(?<!\\d)(\\d{6})(?!\\d)', 1), '')))
      WHEN funder_id = 4320334593 THEN (CAST(CAST(COALESCE(NULLIF(regexp_extract(_n, '[A-Z]{3,7}[ /-]?(?:\\d{4})[ -]?(\\d{4,6})$', 1), ''), NULLIF(regexp_extract(_n, '(?<!\\d)(\\d{5,6})(?!\\d)', 1), '')) AS BIGINT) AS STRING))
      WHEN funder_id = 4320320883 THEN (CASE WHEN NULLIF(regexp_extract(regexp_replace(_n,' ',''),'(?:ANR-?)?(\\d{2})-([A-Z0-9]{2,6})-(\\d{4})',1),'') IS NOT NULL THEN CONCAT(regexp_extract(regexp_replace(_n,' ',''),'(?:ANR-?)?(\\d{2})-([A-Z0-9]{2,6})-(\\d{4})',1),'-',regexp_extract(regexp_replace(_n,' ',''),'(?:ANR-?)?(\\d{2})-([A-Z0-9]{2,6})-(\\d{4})',2),'-',regexp_extract(regexp_replace(_n,' ',''),'(?:ANR-?)?(\\d{2})-([A-Z0-9]{2,6})-(\\d{4})',3)) END)
      WHEN funder_id = 4320320924 THEN (CAST(CAST(CASE WHEN _n rlike '^\\d{12}$' THEN SUBSTR(_n,7) ELSE NULLIF(regexp_extract(_n, '(\\d{4,6})$', 1), '') END AS BIGINT) AS STRING))
      WHEN funder_id = 4320311904 THEN (LPAD(NULLIF(regexp_extract(_n, '^(\\d{5,6})(?:[/_ ][A-Z](?:[/_ ]\\d{2})?([/_ ][A-Z])?)?$', 1), ''),6,'0'))
      WHEN funder_id = 4320334627 THEN (NULLIF(regexp_replace(_n,' ',''),''))
      WHEN funder_id = 2461203286 THEN (NULLIF(regexp_replace(regexp_replace(_n,'^(MOST|NSC|NSTC)[ -]*',''),'[ -]',''),''))
      WHEN funder_id = 4320334506 THEN (CAST(CAST(NULLIF(regexp_extract(regexp_replace(regexp_replace(_n,'^[#]+ ?',''),'^(950[- ]|[A-Z]{2,4}[- ]?)',''),'^(\\d{4,6})([-_]\\d+)?$',1),'') AS BIGINT) AS STRING))
      WHEN funder_id = 4320306230 THEN (NULLIF(regexp_replace(_n,' ',''),''))
    END
  END,
  CASE WHEN award_id IS NULL THEN NULL WHEN LENGTH(REGEXP_REPLACE(LOWER(award_id), '[^a-z0-9]', '')) >= 4 THEN REGEXP_REPLACE(LOWER(award_id), '[^a-z0-9]', '') ELSE LOWER(TRIM(award_id)) END
) FROM _t;

-- Verdict per deposited id (feeds the junk guard; read-only w.r.t. awards flow):
--   confirmed           key uniquely hits the funder's registry
--   confirmed_ambiguous key hits >1 registry award (renewal-year families)
--   plausible           fits the funder's id grammar, no registry hit
--   garbage             neither (salvage chain runs before any suppression)
-- Unconfigured funders get verdict 'unscored'.
CREATE OR REPLACE TABLE openalex.awards.award_id_verdicts
USING delta
AS
WITH dep AS (
  SELECT DISTINCT funder_id, funder_award_id
  FROM openalex.awards.openalex_awards_raw
  WHERE provenance IN ('crossref_work_funders','crossref_work.grants','crossref_work','europepmc_work_funders','datacite_work_funders') AND funder_award_id IS NOT NULL
),
reg AS (
  SELECT funder_id, openalex.awards.award_norm_key(funder_id, funder_award_id, 'registry') AS nk,
         COUNT(DISTINCT id) AS n_awards
  FROM openalex.awards.openalex_awards_raw
  WHERE priority >= 3 AND funder_award_id IS NOT NULL
  GROUP BY 1, 2
),
keyed AS (
  SELECT funder_id, funder_award_id, _n,
    openalex.awards.award_norm_key(funder_id, funder_award_id, 'deposited') AS nk
  FROM (SELECT funder_id, funder_award_id,
          regexp_replace(regexp_replace(regexp_replace(UPPER(TRIM(funder_award_id)), '[\\u2010-\\u2015\\u2212\\uFE58\\uFE63\\uFF0D]', '-'), '[\\u00A0\\u1680\\u2000-\\u200B\\u202F\\u205F\\u3000]', ' '), '  +', ' ') AS _n
        FROM dep)
),
scored AS (
  SELECT k.funder_id, k.funder_award_id, k.nk, r.n_awards,
    CASE
      WHEN k.funder_id = 4320321001 THEN (k._n rlike '(?<!\\d)\\d{8}(?!\\d)')
      WHEN k.funder_id = 4320332161 THEN (k._n rlike '[A-Z]\\d{2} ?-?[A-Z]{2} ?-?\\d{5,6}' or k._n rlike '^[A-Z]{2} ?-?\\d{5,6}')
      WHEN k.funder_id = 4320306076 THEN (k._n rlike '^([A-Z]{2,5}[ -]?)?\\d{7}$')
      WHEN k.funder_id = 4320334764 THEN (k._n rlike '^(KAKENHI|JP|NO\\.?|GRANT)?[ -]*(\\d{2}[A-Z]\\d{5}|\\d{8})$')
      WHEN k.funder_id = 4320320879 THEN (k._n rlike '^(SFB|TRR|CRC|EXC|GRK|RTG|FOR|SPP|INST|NFDI|KFO|FZT) ?/?-?\\d+' or k._n rlike '^(DFG[ -])?[A-Z]{1,4} ?\\d{2,4}(/\\d+)?(-\\d+)?( .*)?$' or k._n rlike '(?<!\\d)\\d{9}(?!\\d)')
      WHEN k.funder_id = 4320322795 THEN (regexp_replace(regexp_replace(k._n,'^(MOST|NSC|NSTC)[ -]*',''),'[ -]','') rlike '^\\d{6,7}[A-Z]\\d{6}(MY\\d)?E?\\d?$')
      WHEN k.funder_id = 4320320997 THEN (k._n rlike '(?<!\\d)\\d{2,4}/\\d{4,5}-\\d(?!\\d)')
      WHEN k.funder_id = 4320334779 THEN (k._n rlike '^[A-Z0-9 ./-]+$' and (k._n rlike '/' or k._n rlike '^\\d{4}\\.\\d{5}\\.'))
      WHEN k.funder_id = 4320320300 THEN (k._n rlike '^(GA ?N?°? ?)?\\d{6}$' or k._n rlike '^101\\d{6}$' or k._n rlike '-CT-\\d{4}-' or k._n rlike '(FP[567]|H2020|HORIZON|MSCA|ERC|GA) ?N?°? ?-?\\d{6}')
      WHEN k.funder_id = 4320334593 THEN (k._n rlike '^[A-Z]{3,7}[ /-]?\\d{4}[ -]?\\d{4,6}$' or k._n rlike '^[A-Z]{3,7}[ -]?\\d{4,6}([ -]?\\d{2,4})?$' or k._n rlike '^\\d{5,6}([ -]?\\d{2,4})?$')
      WHEN k.funder_id = 4320320883 THEN (regexp_replace(k._n,' ','') rlike '(ANR-?)?\\d{2}-[A-Z0-9]{2,6}-\\d{4}')
      WHEN k.funder_id = 4320320924 THEN (k._n rlike '^[0-9A-Z]{0,8}[_-]?\\d{4,6}$' or k._n rlike '^\\d{12}$')
      WHEN k.funder_id = 4320311904 THEN (k._n rlike '^\\d{5,6}([/_ ][A-Z][/_ ]\\d{2}[/_ ][A-Z])?$')
      WHEN k.funder_id = 4320334627 THEN (regexp_replace(k._n,' ','') rlike '^EP/[A-Z0-9]{6,7}/[0-9]$' or k._n rlike '^\\d{7}$')
      WHEN k.funder_id = 2461203286 THEN (regexp_replace(regexp_replace(k._n,'^(MOST|NSC|NSTC)[ -]*',''),'[ -]','') rlike '^\\d{6,7}[A-Z]\\d{6}(MY\\d)?E?\\d?$')
      WHEN k.funder_id = 4320334506 THEN (k._n rlike '^#? ?(950[- ])?([A-Z]{2,4}[- ]?)?\\d{4,6}([-_]\\d+)?$')
      WHEN k.funder_id = 4320306230 THEN (regexp_replace(k._n,' ','') rlike '^\\d{2}[A-Z]{2,10}\\d{4,9}$' or k._n rlike '^\\d{6,9}$')
    END AS grammar_pass
  FROM keyed k
  LEFT JOIN reg r ON r.funder_id = k.funder_id AND r.nk = k.nk
)
SELECT funder_id, funder_award_id, nk, n_awards,
  CASE
    WHEN funder_id NOT IN (4320321001,4320332161,4320306076,4320334764,4320320879,4320322795,4320320997,4320334779,4320320300,4320334593,4320320883,4320320924,4320311904,4320334627,2461203286,4320334506,4320306230) THEN 'unscored'
    WHEN n_awards = 1 AND ((funder_id = 4320334506 AND UPPER(TRIM(funder_award_id)) rlike '^[0-9]{4,6}$') OR (funder_id = 4320311904 AND UPPER(TRIM(funder_award_id)) rlike '^[0-9]{5,6}$') OR (funder_id = 4320320924 AND UPPER(TRIM(funder_award_id)) rlike '^[0-9]{4,6}$') OR (funder_id = 4320320300 AND UPPER(TRIM(funder_award_id)) rlike '^[0-9]{6}$')) THEN 'confirmed_weak'
    WHEN n_awards = 1 THEN 'confirmed'
    WHEN n_awards > 1 THEN 'confirmed_ambiguous'
    WHEN grammar_pass THEN 'plausible'
    ELSE 'garbage'
  END AS verdict,
  current_timestamp() AS scored_date
FROM scored;
