#!/usr/bin/env python3
"""Generate the per-funder award-id key function + verdict table (oxjob #690).

Layers on the 2026-07-31 award-id-audit machinery: award_norm_key() replaces the
inline generic normalized-key CASE in CreateAwards (aliases + collapse) and
WorkAwards (canonical lookup). For the 15 audited funders it applies the
validated translation rule; everywhere else it reproduces the generic key
byte-for-byte, so unconfigured funders are untouched.

Rules source of truth: oxjob #690 audit (2.38M ids, 2026-07-28) — the FUNDERS
dict below mirrors ~/grants-work/690-audit/audit.py and translation-config.yaml.

Family policy (merge onto newest-year record, @kyle-approved 2026-08-03) is
implemented in the notebooks; this generator emits keys + weakness + verdicts.

Usage: python3 scripts/gen_award_norm_key.py [--schema openalex.awards]
Emits notebooks/awards/AwardNormKey.sql (function + verdict table).
"""
import argparse, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
try:
    from award_translation_rules import FUNDERS, NORM  # vendored rules (source of truth: #690 audit)
except ImportError:  # legacy dev path
    sys.path.insert(0, "/tmp"); from rules_src import FUNDERS, NORM

GENERIC = ("CASE WHEN award_id IS NULL THEN NULL "
           "WHEN LENGTH(REGEXP_REPLACE(LOWER(award_id), '[^a-z0-9]', '')) >= 4 "
           "THEN REGEXP_REPLACE(LOWER(award_id), '[^a-z0-9]', '') "
           "ELSE LOWER(TRIM(award_id)) END")

# Funders whose registry keys are bare numbers in a dense space: a deposited
# id that is ONLY a bare number can coincidentally hit the registry (measured
# 2026-08-03: 23.4% of foreign numerics hit CIHR's 77k keys). Matches whose
# deposited form has no self-identifying structure get verdict confirmed_weak:
# kept + flagged, NEVER auto-merged. Self-identifying forms (prefix, 950-,
# _1 suffix, /Z/16/Z, scheme codes) stay 'confirmed'.
WEAK_BARE = {
  4320334506: r"^[0-9]{4,6}$",          # CIHR (foreign-hit 15.4%)
  4320311904: r"^[0-9]{5,6}$",          # Wellcome bare cores (3.2% but native-bare stream)
  4320320924: r"^[0-9]{4,6}$",          # SNSF bare numbers (17.3%)
  4320320300: r"^[0-9]{6}$",            # EC bare FP-era GAs (19.0%)
  4320306076: r"^[0-9]{7}$",            # NSF bare 7-digit (39.6% — worst measured; review F2)
  4320334593: r"^[0-9]{4,6}$",          # NSERC bare serials (19.9%; 70% 4-digit density; review F2)
}

AGG_PROV = ("'crossref_work_funders','crossref_work.grants','crossref_work',"
            "'europepmc_work_funders','datacite_work_funders'")


def case_over(field):
    return "\n".join(
        f"      WHEN funder_id = {r['fid']} THEN ({r[field].replace('norm', '_n')})"
        for r in FUNDERS.values())


def gram_case():
    return "\n".join(
        f"      WHEN k.funder_id = {r['fid']} THEN ({r['gram'].replace('norm', 'k._n')})"
        for r in FUNDERS.values())


def gen(schema):
    norm_expr = NORM.format(c="award_id")
    fids = ",".join(str(r["fid"]) for r in FUNDERS.values())
    norm_expr2 = NORM.format(c="award_id")
    weak_cond_fn = " OR ".join(
        f"(funder_id = {fid} AND _n rlike '{pat}')"
        for fid, pat in WEAK_BARE.items()) or "FALSE"
    weak_cond = " OR ".join(
        f"(funder_id = {fid} AND _n rlike '{pat}')"
        for fid, pat in WEAK_BARE.items()) or "FALSE"
    return f"""-- GENERATED by scripts/gen_award_norm_key.py — DO NOT EDIT BY HAND.
-- Per-funder award-id translation key (oxjob #690), layered on the 2026-07-31
-- award-id-audit generic key. Family policy (merge onto newest year,
-- @kyle 2026-08-03) lives in the NOTEBOOKS (CreateAwards/WorkAwards) — this
-- file only defines keys, weakness, and verdicts.

-- Weakness predicate (review F1/F8): TRUE when a deposited string's NORMALIZED
-- form is a bare number at a dense-numeric-registry funder — such evidence is
-- never sufficient for an automatic merge. Single source of truth: WEAK_BARE.
CREATE OR REPLACE FUNCTION {schema}.award_id_is_weak(funder_id BIGINT, award_id STRING)
RETURNS BOOLEAN
RETURN
WITH _t AS (SELECT {norm_expr2} AS _n)
SELECT COALESCE({weak_cond_fn}, FALSE) FROM _t;

CREATE OR REPLACE FUNCTION {schema}.award_norm_key(funder_id BIGINT, award_id STRING, side STRING)
RETURNS STRING
RETURN
WITH _t AS (SELECT {norm_expr} AS _n)
SELECT COALESCE(
  CASE WHEN side = 'registry' THEN
    CASE
{case_over('rkey')}
    END
  ELSE
    CASE
{case_over('xkey')}
    END
  END,
  {GENERIC}
) FROM _t;

-- Verdict per deposited id (feeds the junk guard; read-only w.r.t. awards flow):
--   confirmed           key uniquely hits the funder's registry
--   confirmed_ambiguous key hits >1 registry award (renewal-year families)
--   plausible           fits the funder's id grammar, no registry hit
--   garbage             neither (salvage chain runs before any suppression)
-- Unconfigured funders get verdict 'unscored'.
CREATE OR REPLACE TABLE {schema}.award_id_verdicts
USING delta
AS
WITH dep AS (
  SELECT DISTINCT funder_id, funder_award_id
  FROM openalex.awards.openalex_awards_raw
  WHERE provenance IN ({AGG_PROV}) AND funder_award_id IS NOT NULL
),
reg AS (
  SELECT funder_id, {schema}.award_norm_key(funder_id, funder_award_id, 'registry') AS nk,
         COUNT(DISTINCT id) AS n_awards
  FROM openalex.awards.openalex_awards_raw
  WHERE priority >= 3 AND funder_award_id IS NOT NULL
  GROUP BY 1, 2
),
keyed AS (
  SELECT funder_id, funder_award_id, _n,
    {schema}.award_norm_key(funder_id, funder_award_id, 'deposited') AS nk
  FROM (SELECT funder_id, funder_award_id,
          {NORM.format(c="funder_award_id")} AS _n
        FROM dep)
),
scored AS (
  SELECT k.funder_id, k.funder_award_id, k._n, k.nk, r.n_awards,
    CASE
{gram_case()}
    END AS grammar_pass
  FROM keyed k
  LEFT JOIN reg r ON r.funder_id = k.funder_id AND r.nk = k.nk
)
SELECT funder_id, funder_award_id, nk, n_awards,
  CASE
    WHEN funder_id NOT IN ({fids}) THEN 'unscored'
    -- review F3: weak surface-form is checked FIRST — a bare number is weak
    -- evidence regardless of how many registry awards it happens to hit
    WHEN n_awards >= 1 AND ({weak_cond}) THEN 'confirmed_weak'
    WHEN n_awards = 1 THEN 'confirmed'
    WHEN n_awards > 1 THEN 'confirmed_ambiguous'
    WHEN grammar_pass THEN 'plausible'
    ELSE 'garbage'
  END AS verdict,
  current_timestamp() AS scored_date
FROM scored;
"""


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--schema", default="openalex.awards")
    a = ap.parse_args()
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..",
                       "notebooks", "awards", "AwardNormKey.sql")
    open(out, "w").write(gen(a.schema))
    print(f"wrote {os.path.normpath(out)} (schema={a.schema})")
