#!/usr/bin/env python3
"""Generate the per-funder award-id key function + verdict table (oxjob #690).

Layers on the 2026-07-31 award-id-audit machinery: award_norm_key() replaces the
inline generic normalized-key CASE in CreateAwards (aliases + collapse) and
WorkAwards (canonical lookup). For the 15 audited funders it applies the
validated translation rule; everywhere else it reproduces the generic key
byte-for-byte, so unconfigured funders are untouched.

Rules source of truth: oxjob #690 audit (2.38M ids, 2026-07-28) — the FUNDERS
dict below mirrors ~/grants-work/690-audit/audit.py and translation-config.yaml.

MERGE_FAMILIES knob: when one sharp key matches MULTIPLE registry awards (NIH
renewal-year lineages: ~375k keys, avg 5.3 rows), True = collapse deposits onto
the newest year's record; False = leave those groups un-collapsed (flagged in
the verdict table as confirmed_ambiguous). Flip + regenerate on Kyle's call.

Usage: python3 scripts/gen_award_norm_key.py [--schema openalex.awards]
       [--merge-families true|false]
Emits notebooks/awards/AwardNormKey.sql (function + verdict table).
"""
import argparse, os, sys

sys.path.insert(0, "/tmp")
from rules_src import FUNDERS, NORM  # validated per-funder SQL exprs (over `norm`)

GENERIC = ("CASE WHEN award_id IS NULL THEN NULL "
           "WHEN LENGTH(REGEXP_REPLACE(LOWER(award_id), '[^a-z0-9]', '')) >= 4 "
           "THEN REGEXP_REPLACE(LOWER(award_id), '[^a-z0-9]', '') "
           "ELSE LOWER(TRIM(award_id)) END")

# Funders whose registry keys are bare numbers in a dense space: a deposited
# id that is ONLY a bare number can coincidentally hit the registry (measured
# 2026-08-03: 23.4% of foreign numerics hit CIHR's 77k keys). Matches whose
# deposited form has no self-identifying structure get verdict confirmed_weak:
# kept + flagged, NEVER auto-merged. Self-identifying forms (prefix, 950-,
# _1 suffix, /Z/16/Z, scheme codes) stay 'confirmed'.
WEAK_BARE = {
  4320334506: r"^[0-9]{4,6}$",          # CIHR
  4320311904: r"^[0-9]{5,6}$",          # Wellcome bare cores
  4320320924: r"^[0-9]{4,6}$",          # SNSF bare numbers
  4320320300: r"^[0-9]{6}$",            # EC bare FP-era GAs
}

AGG_PROV = ("'crossref_work_funders','crossref_work.grants','crossref_work',"
            "'europepmc_work_funders','datacite_work_funders'")


def case_over(field):
    return "\n".join(
        f"      WHEN funder_id = {r['fid']} THEN ({r[field].replace('norm', '_n')})"
        for r in FUNDERS.values())


def gram_case():
    return "\n".join(
        f"      WHEN k.funder_id = {r['fid']} THEN ({r['gram'].replace('norm', 'k._n')})"
        for r in FUNDERS.values())


def gen(schema, merge_families):
    norm_expr = NORM.format(c="award_id")
    fids = ",".join(str(r["fid"]) for r in FUNDERS.values())
    weak_cond = " OR ".join(
        f"(funder_id = {fid} AND UPPER(TRIM(funder_award_id)) rlike '{pat}')"
        for fid, pat in WEAK_BARE.items()) or "FALSE"
    return f"""-- GENERATED by scripts/gen_award_norm_key.py — DO NOT EDIT BY HAND.
-- Per-funder award-id translation key (oxjob #690), layered on the 2026-07-31
-- award-id-audit generic key. MERGE_FAMILIES={merge_families}.

CREATE OR REPLACE FUNCTION {schema}.award_norm_key(funder_id BIGINT, award_id STRING, side STRING)
RETURNS STRING
RETURN
WITH _t AS (SELECT {norm_expr} AS _n)
SELECT COALESCE(
  CASE WHEN side = 'registry' THEN
    CASE
{case_over('rkey')}
    END
  ELSE
    CASE
{case_over('xkey')}
    END
  END,
  {GENERIC}
) FROM _t;

-- Verdict per deposited id (feeds the junk guard; read-only w.r.t. awards flow):
--   confirmed           key uniquely hits the funder's registry
--   confirmed_ambiguous key hits >1 registry award (renewal-year families)
--   plausible           fits the funder's id grammar, no registry hit
--   garbage             neither (salvage chain runs before any suppression)
-- Unconfigured funders get verdict 'unscored'.
CREATE OR REPLACE TABLE {schema}.award_id_verdicts
USING delta
AS
WITH dep AS (
  SELECT DISTINCT funder_id, funder_award_id
  FROM openalex.awards.openalex_awards_raw
  WHERE provenance IN ({AGG_PROV}) AND funder_award_id IS NOT NULL
),
reg AS (
  SELECT funder_id, {schema}.award_norm_key(funder_id, funder_award_id, 'registry') AS nk,
         COUNT(DISTINCT id) AS n_awards
  FROM openalex.awards.openalex_awards_raw
  WHERE priority >= 3 AND funder_award_id IS NOT NULL
  GROUP BY 1, 2
),
keyed AS (
  SELECT funder_id, funder_award_id, _n,
    {schema}.award_norm_key(funder_id, funder_award_id, 'deposited') AS nk
  FROM (SELECT funder_id, funder_award_id,
          {NORM.format(c="funder_award_id")} AS _n
        FROM dep)
),
scored AS (
  SELECT k.funder_id, k.funder_award_id, k.nk, r.n_awards,
    CASE
{gram_case()}
    END AS grammar_pass
  FROM keyed k
  LEFT JOIN reg r ON r.funder_id = k.funder_id AND r.nk = k.nk
)
SELECT funder_id, funder_award_id, nk, n_awards,
  CASE
    WHEN funder_id NOT IN ({fids}) THEN 'unscored'
    WHEN n_awards = 1 AND ({weak_cond}) THEN 'confirmed_weak'
    WHEN n_awards = 1 THEN 'confirmed'
    WHEN n_awards > 1 THEN 'confirmed_ambiguous'
    WHEN grammar_pass THEN 'plausible'
    ELSE 'garbage'
  END AS verdict,
  current_timestamp() AS scored_date
FROM scored;
"""


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--schema", default="openalex.awards")
    ap.add_argument("--merge-families", default="false")
    a = ap.parse_args()
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..",
                       "notebooks", "awards", "AwardNormKey.sql")
    open(out, "w").write(gen(a.schema, a.merge_families))
    print(f"wrote {os.path.normpath(out)} (schema={a.schema}, merge_families={a.merge_families})")
